---
- name: "Build Image and run container with ansible playbook"
  hosts: localhost
  tasks:
# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: build docker image from dockerfile
    command: docker build -t triple3a/laravel-app .  
# Make sure to change the image name with your personal dockerhub account and reposiroty 
  - name: push image to dockerhub
    command: docker push triple3a/laravel-app 



  